[project]
name = "mynote"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "keyboard>=0.13.5",
    "pyinstaller>=6.16.0",
    "tkcalendar>=1.6.1",
]
